repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/streetsidesoftware/cspell-cli
  rev: v8.3.0
  hooks:
    - id: cspell
      types: [markdown]
